### ISSUE TITLE
\elementname

### ISSUE THREAD

**Issue by MEGRETP** [cgnieder/elements#3]
The command `\elementname{Po}` always prints the element name with the first letter as a capital letter.

In French document except at the beginning of a sentence, the element name is written with a small letter.
I have tried to use `\MaketextLowercase{\elementname{Po}` but without success.

Would it possible to have an option `\elementname[opt]{sym|Z}` that lets the user choose the text formatting (all letters upper, all letters lower, first letter upper)?

**Comment by cgnieder** [comment]
How about this?

```latex
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[french]{babel}

\usepackage{elements}

\let\Elementname\elementname

\renewrobustcmd*\elementname[1]{%
  \saveelementname\tmp{#1}%
  \MakeLowercase{\tmp}%
}

\begin{document}

\Elementname{Po}
\elementname{Po}

\end{document}
```

**Comment by cgnieder** [comment]
Regarding the other question: this is straightforward from the suggestion in my first comment:

```latex
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[french]{babel}

\usepackage{elements}

\renewrobustcmd*\elementname[2][]{%
  \begingroup
    \saveelementname\tmp{#2}%
    #1{\tmp}%
  \endgroup
}

\begin{document}

\elementname{13}
\elementname[\MakeLowercase]{13}
\elementname[\textit]{13}
\elementname[\itshape\MakeLowercase]{13}

\end{document}
```

**Comment by MEGRETP** [comment]
Thanks a lot.
It perfectly feeds my needs.

**Comment by MEGRETP** [comment]
Just for my information, I looked into the code and I cannot figure out why the simple command \MakeLowecase{\elementname{Po}} does not work whereas \tetxbf{\elementname{Po}} works?

**Comment by cgnieder** [comment]
Font commands just switch to other instructions for typesetting. `\textbf{foo}` *very roughly* corresponds to `{\bfseries foo}` so doesn't really need to do anything with its argument… The argument just needs to be inside a group along with the font switch.

`\MakeLowercase` transforms its argument so it needs to completely expand its argument until there is only text before it can make its transformation.

`\elementname` does non-expandable steps which is why `\MakeLowecase{\elementname{Po}}` doesn't work.

**Comment by MEGRETP** [comment]
Thanks a lot.
